### Register
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "name": "test22",
  "email": "test22ttt@example.com",
  "password": "test22"
}


### Login 
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "test22ttt@example.com",
  "password": "test22"
}

######################################
### Surveys
######################################
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0ZXN0MjJ0dHRAZXhhbXBsZS5jb20iLCJleHAiOjE2NDY4OTUzMTh9.NQDZPdWf9txIkOjuynLVQVq8YL0q47Yva8bJ-JtPYXnLAN3-rs_eW2qMpbXlJEDnyjItpiAkoir-3Cm27o2veQ 
### Get all survey for user
GET http://localhost:8000/api/survey/
Content-Type: application/json
Authorization: Bearer {{token}}

### Create Survey
POST http://localhost:8000/api/survey
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Survey New for creation",
  "description": "This is a May 9th new survey"
}

### FindSingle Survey
GET http://localhost:8000/api/survey/622989f5cb8658738afa26fd
Content-Type: application/json
Authorization: Bearer {{token}}

### Update Survey
PUT http://localhost:8000/api/survey/622486a3722c49e3de9755b0
Content-Type: application/json

{
  "name": "Survey Update WTC, haha and haha",
  "description": "This is an Update survey, It's not well done"
}

### Delete a Survey
DELETE  http://localhost:8000/api/survey/621e0eb0466ea9c2e5b32c9f
